app:
  domain: https://dev0shopbos.pulmuone.online
  static-resource-cache-period: 0   # 개발 서버에서는 static resource 의 cache 미적용
  storage:
    public:
      public-url-path: /pulmuone/public  # public 파일 접근 url
      public-root-location: /data/dev_image   # public 파일의 최상위 저장경로
      public-storage-url: https://sdev0.pulmuone.app/  # 개발 서버와 연동된 public 저장소 url
      public-cdn-url: https://sdev0.pulmuone.app/  # 개발서버는 CDN 사용 안함 storage url 과 동일
  secretKey: '#PMO_HGRM'

spring:
  application:
    name: pmo-batch-eon
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      master:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://db-665ft.vpc-cdb.ntruss.com:3306/pulmuone_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
        username: dev_hangaram
        password: vnfandnjs##77
        maxLifetime: 3540000
        connectionTimeout: 60000
      slave-eon:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://192.1.5.39:1433;databaseName=new
        username: eon
        password: eon2003
        maxLifetime: 1800000
        connectionTimeout: 60000

logging:
  config: classpath:logback-spring.xml
  level:
    kr:
      co:
        pulmuone:
          batch: DEBUG
  file:
    name: pmo-batch-eon
    path: /data/dev_logs/BATCH

jasypt:
  encryptor:
    password: devpmobatch

system_cache:
  api_domain: https://qashop.pulmuone.online/
  cache_file_path: /cache
  cache_file_name: apiCacheList.json

resource:
  server:
    url:
      bos: https://dev0shopbos.pulmuone.online
      mall: https://dev0shop.pulmuone.online
      image: https://sdev0.pulmuone.app

eon:
  sender:
    mail: pmocs_02@pulmuone.com
    nm: 풀무원
  return:
    mail: pmocs_02@pulmuone.com

database:
  encryption:
    key: lssCSGhjyCBS!@34

slack:
  channel: hangaram_noti_dev_bach

shoplive:
  access_key: xe9XZmy2pEIuNRirpdVC
  secret_key: OUdsYktjVDdRYUFyVXQwU0VoYXFqZTVidk0xdXNzNEk=