app:
  domain: https://shopbos.pulmuone.co.kr
  static-resource-cache-period: 0   # 개발 서버에서는 static resource 의 cache 미적용
  storage:
    public:
      public-url-path: /pulmuone/public  # public 파일 접근 url
      public-root-location: /data/image   # public 파일의 최상위 저장경로
      public-storage-url: https://s.pulmuone.app/  # 개발 서버와 연동된 public 저장소 url
      public-cdn-url: https://shoppulmuone.cdn.ntruss.com/  # 운영 ncloud CDN url
  secretKey: '#PMO_HGRM'

spring:
  application:
    name: pmo-batch-eon
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://db-896d7.vpc-cdb.ntruss.com:3306/prod_pulmuone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
        username: prod_hangaram
        password: vnfandnjs##77
        maxLifetime: 540000
        connectionTimeout: 60000
      slave-eon:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://192.1.5.39:1433;databaseName=new
        username: eon
        password: eon2003
        maxLifetime: 1800000
        connectionTimeout: 60000

logging:
  config: classpath:logback-spring.xml
  level:
    kr:
      co:
        pulmuone:
          batch: ERROR
  file:
    name: pmo-batch-eon
    path: /data/logs/BATCH

jasypt:
  encryptor:
    password: devpmobatch

system_cache:
  api_domain: https://shop.pulmuone.co.kr
  cache_file_path: /cache
  cache_file_name: apiCacheList.json

resource:
  server:
    url:
      bos: https://shopbos.pulmuone.co.kr/
      mall: https://shop.pulmuone.co.kr
      image: https://s.pulmuone.app

eon:
  sender:
    mail: pmocs_02@pulmuone.com
    nm: 풀무원
  return:
    mail: pmocs_02@pulmuone.com

database:
  encryption:
    key: lssCSGhjyCBS!@

slack:
  channel: hangaram_noti_prod_bach

shoplive:
  access_key: xe9XZmy2pEIuNRirpdVC
  secret_key: OUdsYktjVDdRYUFyVXQwU0VoYXFqZTVidk0xdXNzNEk=