app:
  domain: https://canshop.pulmuone.online
  static-resource-cache-period: 0   # 개발 서버에서는 static resource 의 cache 미적용
  storage:
    public:
      public-url-path: /pulmuone/public  # public 파일 접근 url
      public-root-location: /data/image   # public 파일의 최상위 저장경로
      public-storage-url: https://scan.pulmuone.app/  # 개발 서버와 연동된 public 저장소 url
      public-cdn-url: https://shoppulmuone.cdn.ntruss.com/  # 운영 ncloud CDN url(검증 서버 CDN 테스트)
  secretKey: '#PMO_HGRM'

spring:
  profiles: ver
  datasource:
    hikari:
      master:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://db-896d7.vpc-cdb.ntruss.com:3306/prod_pulmuone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
        username: prod_hangaram
        password: vnfandnjs##77
        #        cachePrepStmts: true
        #        prepStmtCacheSize: 250
        #        prepStmtCacheSqlLimit: 2048
        #        useServerPrepStmts: true
        #        useLocalSessionState: true
        #        rewriteBatchedStatements: true
        #        cacheResultSetMetadata: true
        #        cacheServerConfiguration: true
        #        elideSetAutoCommits: true
        #        maintainTimeStats: false
        minimumIdle: 10
        maximumPoolSize: 100
        maxLifetime: 540000
        mybatis:
          config-location: classpath:profiles/ver/sql-mapper-config-ver.xml
      slave-erp:
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@192.1.5.160:1523:prod
        username: PMOESHOPERP
        password: PMOESHOPERP
        #        cachePrepStmts: true
        #        prepStmtCacheSize: 250
        #        prepStmtCacheSqlLimit: 2048
        #        useServerPrepStmts: true
        #        useLocalSessionState: true
        #        rewriteBatchedStatements: true
        #        cacheResultSetMetadata: true
        #        cacheServerConfiguration: true
        #        elideSetAutoCommits: true
        #        maintainTimeStats: false
        minimumIdle: 1
        maximumPoolSize: 1
        mybatis:
          config-location: classpath:profiles/ver/sql-mapper-config-ver.xml
      slave-cj-front:
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@210.98.159.153:1523:OPENDBT
        username: pulmuone
        password: pulmuone123
        #        cachePrepStmts: true
        #        prepStmtCacheSize: 250
        #        prepStmtCacheSqlLimit: 2048
        #        useServerPrepStmts: true
        #        useLocalSessionState: true
        #        rewriteBatchedStatements: true
        #        cacheResultSetMetadata: true
        #        cacheServerConfiguration: true
        #        elideSetAutoCommits: true
        #        maintainTimeStats: false
        minimumIdle: 1
        maximumPoolSize: 1
        mybatis:
          config-location: classpath:profiles/ver/sql-mapper-config-ver.xml
      slave-ecs:
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        jdbc-url: jdbc:tibero:thin:@192.1.5.205:8629:ECSDB
        username: ECS_IF_USER
        password: ECS_IF_USER
        #        cachePrepStmts: true
        #        prepStmtCacheSize: 250
        #        prepStmtCacheSqlLimit: 2048
        #        useServerPrepStmts: true
        #        useLocalSessionState: true
        #        rewriteBatchedStatements: true
        #        cacheResultSetMetadata: true
        #        cacheServerConfiguration: true
        #        elideSetAutoCommits: true
        #        maintainTimeStats: false
        minimumIdle: 5
        maximumPoolSize: 50
        mybatis:
          config-location: classpath:profiles/ver/sql-mapper-config-ver.xml
      slave-pov:
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@172.17.1.131:1521:POV
        username: PMOODS
        password: essbase
        #        cachePrepStmts: true
        #        prepStmtCacheSize: 250
        #        prepStmtCacheSqlLimit: 2048
        #        useServerPrepStmts: true
        #        useLocalSessionState: true
        #        rewriteBatchedStatements: true
        #        cacheResultSetMetadata: true
        #        cacheServerConfiguration: true
        #        elideSetAutoCommits: true
        #        maintainTimeStats: false
        minimumIdle: 5
        maximumPoolSize: 50
        mybatis:
          config-location: classpath:profiles/ver/sql-mapper-config-ver.xml

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: redisc-748b2.vpc-cdb.ntruss.com
    port: 6379

  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 200MB

logging:
  config: classpath:profiles/ver/logback-spring-ver.xml

# ERP API request / connection-pooling 정보
erp-api-exchange:
  scheme: https
  api-server-url: rsif.pulmuone.com
  auth-key: 61e4e9f4-d382-44ea-8278-2aaf63ec16b9
  request-timeout:
    connect-timeout: 15   # 서버에 소켓 연결을 맺을 때의 타임아웃 ( 단위 : 초 )
    connection-request-timeout: 15   # Connection Pool 로부터 꺼내올 때의 타임아웃 ( 단위 : 초 )
    read-timeout: 30   # 읽기시간초과 ( 단위 : 초 )
  connection-pooling:
    max-conn-total: 100   # 최대 커넥션 갯수
    max-conn-per-route: 20   # IP/domain port 하나 당 최대 커넥션 갯수

lotteglogis:
  tracking:
    scheme: https
    host: ftr.alps.llogis.com
    port: 18260
    path: /openapi/ftr/getCustmerNviewTracking
  client-order:
    auth-key: IgtAK eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJDMDExNTQ1IiwiYXVkIjoiQzAxMTU0NSIsIm5hbWUiOiJwbW9fZGV2IiwiZXhwIjoxNTM1MTM1NTk5OTk5LCJpYXQiOjE2MDA4Mzg4MzV9.h_ei_xGdGdsoupTUpw5WDNsuWaivpYFW6xK1RoGcdvI
    scheme: http
    host: apigw.llogis.com
    port: 10110
    path: /api/pid/cus/714a/apiSndOut

cjlogistics:
  tracking:
    scheme: http
    host: tracking.doortodoor.co.kr
    path: /json_comn_info

ezadmin:
  partner-key: 6a9cbce1b364948918cb982f61b039e7
  domain-key: 6a9cbce1b3649489b576c50befb04ad04b38cdf15a11b5c9
  tracking:
    scheme: http
    host: api2.cloud.ezadmin.co.kr
    path: /ezadmin/function.php

# elasticsearch cluster
elasticsearch:
  hosts: 10.31.10.18:9200, 10.31.10.18:9201, 10.31.10.18:9202
  dicDataPath: /data/dic/
  dicDataBackupPath: /data/dic/backup/

database:
  encryption:
    key: lssCSGhjyCBS!@34

naver:
  login:
    clientId: uuEmdRKPmJl6Uu_Y6OBc
    clientSecret: LynDiWzEq2
    redirectUrl: https://canshop.pulmuone.online/user/snsLogin/callbackNaver
    redirectBuyerUrl: https://canshop.pulmuone.online/user/buyer/callbackNaver
    userProfileUrl: https://openapi.naver.com/v1/nid/me
  sms:
    apiUrl: https://sens.apigw.ntruss.com
    requestUrl: /sms/v2/services/
    requestUrlTail: /messages
    serviceId: ncp:sms:kr:258062385037:pulmuone_sms
    accessKeyId: ApZTxOC5V29tVWXA9BWO
    secretKey: QhN00nlomNSpBX3eoc8yjKAVmkt2XdWwFZ19Zfij

kakao:
  login :
    userProfileUrl: https://kapi.kakao.com/v2/user/me

google:
  recaptcha:
    secret: 6LdZALQZAAAAAJ-ho29nvNeCLCI6zmKIoJNHZR9M
  login:
    userProfileUrl: https://oauth2.googleapis.com/tokeninfo?id_token=

facebook:
  login:
    userProfileUrl: https://graph.facebook.com/v10.0/me?access_token=

apple:
  login:
    userProfileUrl: https://appleid.apple.com/auth/keys
    
asis:
  user:
    authorizationKey: Y0cxdllYQnBiR2wyWlE9PQ
    userInfoCheck:
      requestUrl: https://member.pulmuone.co.kr/user_info_check.jsp
    searchCustDelvList:
      requestUrl: http://api.pulmuone.info/hgrm/api/searchCustDelvList
    userSearchId:
      requestUrl: https://member.pulmuone.co.kr/user_search_id.jsp
    searchCustomerRsrvTotal:
      requestUrl: http://api.pulmuone.info/hgrm/api/searchCustRsrvTotal
    minusCustomerRsrv:
      requestUrl: http://api.pulmuone.info/hgrm/api/minusCustRsrv

#본인인증
kmc:
  cpId: PMOM1001
  urlCode: '006001'

inicis:
  account:
    basic:
      mid: pulmuone05
      signKey: aG9oMXVxUnAvdlhkQ2x2ZHVVbkpQdz09
      cancelPassword: 1111
      key: mQyFXCdcLJ8QmJyo
      iv: eBUn08rLoG2Arm==
    admin:
      mid: pulmuone06
      signKey: YlNXbk1Pd1M4NStGRm5pcG9GeFRKUT09
      cancelPassword: 1111
      key: aW1Yo1Jpi2AdXQdE
      iv: rxIxYNcBXQB3wR==
  payScriptUrl: https://stdpay.inicis.com/stdjs/INIStdPay.js
  closeScriptUrl: https://stdpay.inicis.com/stdjs/INIStdPay_close.js
  cardBillUrl: https://iniweb.inicis.com/DefaultWebApp/mall/cr/cm/mCmReceipt_head.jsp?noTid=
  cashBillUrl: https://iniweb.inicis.com/DefaultWebApp/mall/cr/cm/Cash_mCmReceipt.jsp?noTid=

kcp:
  g_conf_log_dir: /data/ver_logs/PG/KCP/
  g_conf_gw_url: paygw.kcp.co.kr
  g_conf_js_url: https://pay.kcp.co.kr/plugin/payplus_web.jsp
  g_conf_server: true
  g_conf_site_name: PULMUONE SHOP
  account:
    basic:
      site_cd: A96G6
      site_key: 020FtP5n8BpbAa8zsPfwISS__
    simple:
      site_cd: A96G7
      site_key: 3ewL4cZxu0KRbfnur4ZRXDl__
    regular:
      site_cd: A96G8
      site_key: 1okDTwsw2o7JBzkZU2TPizd__
      group_id: A96G81054076
  cardBillUrl: https://admin8.kcp.co.kr/assist/bill.BillActionNew.do?cmd=card_bill&tno=
  cashBillUrl: https://admin8.kcp.co.kr/assist/bill.BillActionNew.do?cmd=cash_bill&cash_no=

resource:
  server:
    url:
      bos: https://canshopbos.pulmuone.online
      mall: https://canshop.pulmuone.online
      image: https://scan.pulmuone.app

watson:
  key: k6MbmKiedByEGwY7D9ADoZd49m94C14M2Esmg7wH3C1a
  url: https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers/

udms:
  url: http://121.254.255.34:8080
  userID: PMOSHOP
  authKey: CI78rdqtnus2ZIQCTHJm
  apiId: '030'

slack:
  channel: hangaram_noti_dev_bach

shoplive:
  access_key: xe9XZmy2pEIuNRirpdVC
  secret_key: OUdsYktjVDdRYUFyVXQwU0VoYXFqZTVidk0xdXNzNEk=