CREATE TABLE `ST_BATCH_JOB` (
  `BATCH_NO` bigint(20) unsigned NOT NULL COMMENT '배치번호',
  `BATCH_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '배치명',
  `DESCRIPTION` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '설명',
  `JOB_CLASS_FULL_PATH` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '실행JOB경로',
  `USE_YN` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '사용여부',
  `CREATE_DATE` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  `SCHEDULE` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`BATCH_NO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='배치관리'