app:
  domain: http://localhost:8280
  static-resource-cache-period: 0   # local 환경에서 static resource 의 cache 미적용
  storage:
    public:
      public-url-path: /pulmuone/public  # public 파일 접근 url
      public-root-location: storage   # public 파일의 최상위 저장경로 : Master 프로젝트 디렉토리 기준 상대 경로
      public-storage-url: /  # 로컬에서 public 저장소 url/
      public-cdn-url: /  # 로컬서버는 CDN 사용 안함 storage url 과 동일
  secretKey: '#PMO_HGRM'

spring:
  application:
    name: pmo-batch-cj
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      master:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://db-665ft-kr.vpc-pub-cdb.ntruss.com:3306/pulmuone_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
        username: dev_hangaram
        password: vnfandnjs##77
        maxLifetime: 3540000
      slave-cj:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:oracle:thin:@210.98.159.153:1523:OPENDBT
        username: pulmuone
        password: pulmuone123
        maxLifetime: 1800000

logging:
  config: classpath:logback-spring.xml
  level:
    kr:
      co:
        pulmuone:
          batch: DEBUG
  file:
    name: pmo-batch-cj
    path: ./logs/BATCH

jasypt:
  encryptor:
    password: devpmobatch

system_cache:
  api_domain: https://qashop.pulmuone.online/
  cache_file_path: /cache
  cache_file_name: apiCacheList.json

resource:
  server:
    url:
      bos: https://dev0shopbos.pulmuone.online
      mall: https://dev0shop.pulmuone.online
      image: https://sdev0.pulmuone.app

database:
  encryption:
    key: lssCSGhjyCBS!@34

slack:
  channel: hangaram_noti_dev_bach

shoplive:
  access_key: xe9XZmy2pEIuNRirpdVC
  secret_key: OUdsYktjVDdRYUFyVXQwU0VoYXFqZTVidk0xdXNzNEk=