module-name: BATCH
spring:
  application:
    name: pmo-batch
  output:
    ansi:
      enabled: always
  main:
    web-application-type: none
  profiles:
    active: local

logging:
  config: classpath:logback-spring.xml

#jasypt:
#  encryptor:
#    password: ${PULSHOP_3PL_ENCRYPTION_PASSWORD:}

slack:
  webhook-url: https://hooks.slack.com/services/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
  excludes: local

# elasticsearch cluster
elasticsearch:
  hosts: 49.50.174.15:9200, 101.101.208.222:9200, 101.101.208.223:9200

#FCM
fcm:
  legacy-http-url: https://fcm.googleapis.com/fcm/send