# elasticsearch cluster
elasticsearch:
 hosts: 10.41.227.60:9200, 10.41.230.144:9200, 10.41.154.96:9200

slack:
 webhook-url: https://hooks.slack.com/services/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
 excludes: local