# ------------------------------------------------------------------------
# Pulmuone MALL 모듈 공통 설정 : 해당 모듈 내 모든 profile 이 공유함
# ------------------------------------------------------------------------
module-name: MALL
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # HTTP encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
server:
  error:
    whitelabel:
      enabled: false
  port: 8180

# Swagger 불필요 로그 제거
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR

slack:
  webhook-url: https://hooks.slack.com/services/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
  excludes: local
