# ------------------------------------------------------------------------
# Pulmuone BOS 모듈 공통 설정 : 해당 모듈 내 모든 profile 이 공유함
# ------------------------------------------------------------------------
module-name: BOS
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # HTTP encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
server:
  error:
    whitelabel:
      enabled: false
  port: 8280
  servlet:
    session:
      cookie:
        secure: true


# elasticsearch cluster
elasticsearch:
  hosts: 10.41.227.60:9200, 10.41.230.144:9200, 10.41.154.96:9200

# Swagger 불필요 로그 제거
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR


# mybatis pagination
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  helper-dialect: mysql

slack:
  webhook-url: https://hooks.slack.com/services/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
  excludes: local
