module-name: BATCH_CJ
spring:
  application:
    name: pmo-batch-cj
  output:
    ansi:
      enabled: always
  main:
    web-application-type: none
  profiles:
    active: local

logging:
  config: classpath:logback-spring.xml

slack:
  webhook-url: https://hooks.slack.com/services/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
  excludes: local